### ISSUE TITLE
Supplementary files

### ISSUE THREAD

**Issue by JarrentWu1031** [CVMI-Lab/SC-GS#1]
Nice work! Could you please provide the supplementary files for us to inquire more details? Or is there any time schedule for the code release?

**Comment by yihua7** [comment]
Thank you for your interest in our work! If you could kindly send me an email, we can discuss the details further and establish contact.

**Comment by JarrentWu1031** [comment]
> Thank you for your interest in our work! If you could kindly send me an email, we can discuss the details further and establish contact.

Thanks for your reply! I'll contact you soon!

**Comment by carlinds** [comment]
Hi! I found your work interesting. I would very much like to read the supplementary material referenced in the article. Where can I find that?

Thank you!
