### ISSUE TITLE
Occur an error when install requirements.txt

### ISSUE THREAD

**Issue by irisfreesiri** [CVMI-Lab/SC-GS#10]
error: command 'D:\\Program Files\\CUDA\\v11.8\\bin\\nvcc.exe' failed with exit code 1
ERROR: Failed building wheel for pytorch3d

I've installed CUDA 11.8. When I run the 3D Gaussian Splatting code (https://github.com/jonstephens85/gaussian-splatting-Windows), everything runs well. However, when I installed requirements.txt, I encountered an error. I've tried on my own laptop and the lab's desktop, but both failed.

What else do I need to provide?

**Comment by yihua7** [comment]
Hi,
1. The problem is caused by the failure installation or the incompatibility of pytorch3d. 
2. You may try to **build and install pytorch3d from source** following the instruction in [here](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md) by running:
```
# For Ubuntu
git clone https://github.com/facebookresearch/pytorch3d.git
cd pytorch3d && pip install -e .
```

**Comment by yihua7** [comment]
Hi
Does the above help? Any further problems?

**Comment by irisfreesiri** [comment]
Hi,
Thank you for asking. It doesn't work. Which cuda version should I install?

[cid:77c440ea-80a7-4bc9-b437-48a7308df48e]
________________________________

**Comment by yihua7** [comment]
I am sorry to hear that. Is your CUDA installation compatible with the required version of PyTorch? It is important to ensure that CUDA and pyTorch are compatible with each other to successfully build pyTorch3D.

**Comment by irisfreesiri** [comment]
So which version of CUDA and PyTorch you recommend?

**Comment by yihua7** [comment]
Since you already installed CUDA 11.8, I recommend the following version of pytorch to install:
```
# CUDA 11.8
pip install torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu118
```
Then you can move on to build and install pytorch3d locally. Hope this helps. : )

**Comment by irisfreesiri** [comment]
Hi, thank you for your help. It's already been addressed. I followed these
steps that you sent me the link:
[image: image.png]
1. conda create -n pytorch3d python=3.8

2. conda activate pytorch3d

3. conda install pytorch=1.13.0 torchvision pytorch-cuda=11.6 -c pytorch -c
nvidia

4. conda install -c fvcore -c iopath -c conda-forge fvcore iopath

5. pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113
--extra-index-url  https://download.pytorch.org/whl/cu113

6. pip install "git+https://github.com/facebookresearch/pytorch3d.git"
7. pip install -r requirements.txt
[image: image.png]

It's finally successfully installed.

Thank you for your time and assistance. I really appreciate it!
