### ISSUE TITLE
video output

### ISSUE THREAD

**Issue by zhuhu00** [CVMI-Lab/SC-GS#14]
First of all, congratulations on being accepted by the CVPR2024. This is a very good job. I have a question about the final presentation. How to render these dynamic Gaussians into videos? Is there any code to guide.

**Comment by yihua7** [comment]
Hi, 

1. I just added the button to render the edited motion. 
2. For videos of novel view synthesis, `python render.py --mode all XXX` is what you need.

Hope the above helps : )
