### ISSUE TITLE
A few packages missed in requirements.txt, and share the experience in the installation

### ISSUE THREAD

**Issue by liulisixin** [CVMI-Lab/SC-GS#15]
First, thanks to the authors for creating this incredible project!

I've noticed that a few packages are missing from requirements.txt, which are necessary for the installation process. Adding these packages will ensure that the project runs smoothly:

To prevent train_gui.py from failing, please install:
pip install lpips
pip install pytorch_msssim

Additionally, to avoid runtime errors when interacting with the GUI, install:
pip install matplotlib
pip install scikit-image

Additionally, here is a collection of my installation commands:

 2004  conda create --name scgs python=3.8
 2005  conda activate scgs
 2006  cd PycharmProjects/SC-GS/
 2007  pip install torch==1.13.1+cu116 torchvision==0.14.1+cu116 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu116
 2008  pip install -r requirements.txt  **(Remove torch from the original txt)**
 2010  export TORCH_CUDA_ARCH_LIST="8.6+PTX"  **(This is for the submodules because the setup cannot find GPU info on some machines. This number works for 3090 , check the number for other GPUs. )** 
**(The related error info: arch_list[-1] += '+PTX' IndexError: list index out of range)**
 2011  pip install ./submodules/diff-gaussian-rasterization
 2012  pip install ./submodules/simple-knn
 2014  pip install lpips
 2016  pip install pytorch_msssim
 2019  pip uninstall pytorch3d
 2022  FORCE_CUDA=1 pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable"    **(FORCE_CUDA=1 for forcing the GPU version)**
**(The related error info: pytorch3d, RuntimeError: Not compiled with GPU support.)**
pip install matplotlib
pip install scikit-image
 
In addition, I work on Cuda 11.8 and Linux Ubuntu 20.04.

**Comment by yilan120** [comment]
Thanks for your info, it helps a lot!

**Comment by yihua7** [comment]
Hi,
Many thanks for your kind reminder! I've updated the requirements.txt according to your feedback in the commit 1f835596c85422bb517df8c534cf8aaa6357ac5e. It will help a lot for all users. : )

**Comment by liulisixin** [comment]
> Thanks for your info, it helps a lot!

Great!

**Comment by liulisixin** [comment]
> Hi, Many thanks for your kind reminder! I've updated the requirements.txt according to your feedback in the commit [1f83559](https://github.com/yihua7/SC-GS/commit/1f835596c85422bb517df8c534cf8aaa6357ac5e). It will help a lot for all users. : )

Thank you for your amazing project and work!

**Comment by azzarelli** [comment]
Hi, Thank you to the authors for the code release&paper and thank you to @liulisixin for the solution.

I ran this with cudatoolkit=11.8 and encountered "illegal access memory" error with the gaussian renderer.

[This solution resolved my problems](https://github.com/graphdeco-inria/gaussian-splatting/issues/41#issuecomment-1752279620)
