### ISSUE TITLE
Question about training nerf-ds dataset

### ISSUE THREAD

**Issue by longtermgoals** [CVMI-Lab/SC-GS#18]
First of all, thanks for the brilliant work and sharing with all of us.  I have a question regarding to reproducing nerf-ds dataset results. Since no traiing configurations are specified for this dataset, therefore I used a copy of training script from dnerf dataset, which was:

`
CUDA_VISIBLE_DEVICES=0 python train_gui.py --source_path YOUR/PATH/TO/DATASET/--model_path outputs/cup_novel_view --deform_type node --node_num 512 --hyper_dim 8 --eval --gt_alpha_mask_as_scene_mask --local_frame --resolution 1 --W 800 --H 800
`

The difference was removed --is_blender arguments and change --resolution to 1 in order to avoid extreme scaling. After 2 hours training(for samples as: cup, basin, as), It seems best PSNR remains around 16-17, and the result was almost achieved during the first couple thousands epochs and never gets better since.

I also tried --node_num set to 1024, since it was once mentioned for real-world data, the number of control points should be larger. But  results remain the same.

So I wonder whether we used the wrong script to reproduce the results. Could you please show the parameter settings for nerf-ds dataset to reproduce the results shown in the paper?

Thank you so much in advance!

**Comment by yihua7** [comment]
Hi, you may have a try of the following parameters:

`--deform_type node --node_num 4096 --deform_lr_scale 0.1 --eval --resolution 1 --warm_up 3000 --iterations_node_sampling 10000 --iterations_node_rendering 12000 --oneupSHdegree_step 1000 --progressive_train_node --progressive_stage_ratio 0.1 --progressive_stage_steps 1000 --node_warm_up 1000 --node_enable_densify_prune --no_arap_loss --white_background --gt_alpha_mask_as_dynamic_mask --gs_with_motion_mask --pred_color --dynamic_color_warm_up 20000 --node_densification_interval 3000`

Hope this can help to solve your problem. :)

**Comment by yihua7** [comment]
Hello,

Based on your description, it seems that there may be some issues with the current code, which may be over-adjusted on DNeRF datasets but could potentially degrade on NeRF-DS datasets. If you're in a rush, you can try using our older version, which can be found at this [link](https://pan.baidu.com/s/1UJ85aPGLSyP0_SnDvCovXA?pwd=ik8r) (extraction code: ik8r). The command to run the program is located in the train_gui.sh file. Please note that the code may be messy, so please bear with it and I'm sorry for that.

I apologize for not being able to thoroughly compare the two versions at the moment as I am currently occupied with another project. In the near future, I won't have sufficient time to carefully examine the code. However, I hope that the provided older version will help resolve your issue.

**Comment by longtermgoals** [comment]
Got it!

I was running experiments with the new settings, but it seems to be not working and PSNR stucks at 6000 iterations at around PSNR=16.3. I was worried that I did something wrong. Now it seems to be clear.

Thanks again for the great work and don't worry about it.

**Comment by yihua7** [comment]
Hi,
I just double-checked the code this morning and found that the following command on the old version code works normally on NeRF-DS datasets:

`--deform_type node --node_num 4096 --deform_lr_scale 1 --eval --resolution 1 --gt_alpha_mask_as_dynamic_mask --node_warm_up 500 --iterations_node_sampling 7500 --iterations_node_rendering 10000 --oneupSHdegree_step 5000 --warm_up 3000 --hyper_dim 8 --local_frame --pred_color --pred_opacity --dynamic_color_warm_up 20000 --deform_downsamp_strategy direct`

The PSNR achieves 25.2 around 25000 iterations and is higher in the table in the paper on NeRF-DS (Bell).
![image](https://github.com/yihua7/SC-GS/assets/35869256/8036f4c2-9feb-4e5a-8c29-b2d9aa853aca)
 
Hope this information helps.

**Comment by longtermgoals** [comment]
> Hi, I just double-checked the code this morning and found that the following command on the old version code works normally on NeRF-DS datasets:
> 
> `--deform_type node --node_num 4096 --deform_lr_scale 1 --eval --resolution 1 --gt_alpha_mask_as_dynamic_mask --node_warm_up 500 --iterations_node_sampling 7500 --iterations_node_rendering 10000 --oneupSHdegree_step 5000 --warm_up 3000 --hyper_dim 8 --local_frame --pred_color --pred_opacity --dynamic_color_warm_up 20000 --deform_downsamp_strategy direct`
> 
> The PSNR achieves 25.2 around 25000 iterations and is higher in the table in the paper on NeRF-DS (Bell). ![image](https://private-user-images.githubusercontent.com/35869256/314928306-8036f4c2-9feb-4e5a-8c29-b2d9aa853aca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTgxNDUsIm5iZiI6MTcxMTAxNzg0NSwicGF0aCI6Ii8zNTg2OTI1Ni8zMTQ5MjgzMDYtODAzNmY0YzItOWZlYi00ZTVhLThjMjktYjJkOWFhODUzYWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDEwNDQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MTM5ODQxODVlNjBiYjY3MWI0NDM5ODc2NzIxYmUwMTk3ODM5NWZiMzU3MjJjMGMxYWIwNjE1ZTkwMjVhYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K86RWaml4ZEzwgvbyAXZqW52eV6rlFS_AmOfDSEHFbg)
> 
> Hope this information helps.

Cool, thanks! This makes much more sense now!

**Comment by cdfan0627** [comment]
您好，因為我沒有百度帳號，不知道您能否提供，其他舊程式碼的下載連結讓我下載?

**Comment by cdfan0627** [comment]
您好，請問可以問一下您的舊版程式碼如何Environmental Setups嗎? 因為不管我用新版程式碼的environment或Deformable-3D-Gaussians那篇論文的environment，執行train.py都會一直出現很多環境error。

**Comment by yihua7** [comment]
Hi,
You can try `pip install -r requirements.txt`.
By the way, train.py is not the script to run. Please follow the readme file and use train_gui.py instead. : )

**Comment by zhenyuan1234** [comment]
> Hi, I just double-checked the code this morning and found that the following command on the old version code works normally on NeRF-DS datasets:
> 
> `--deform_type node --node_num 4096 --deform_lr_scale 1 --eval --resolution 1 --gt_alpha_mask_as_dynamic_mask --node_warm_up 500 --iterations_node_sampling 7500 --iterations_node_rendering 10000 --oneupSHdegree_step 5000 --warm_up 3000 --hyper_dim 8 --local_frame --pred_color --pred_opacity --dynamic_color_warm_up 20000 --deform_downsamp_strategy direct`
> 
> The PSNR achieves 25.2 around 25000 iterations and is higher in the table in the paper on NeRF-DS (Bell). ![image](https://private-user-images.githubusercontent.com/35869256/314928306-8036f4c2-9feb-4e5a-8c29-b2d9aa853aca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMjUzNDMsIm5iZiI6MTcyMTIyNTA0MywicGF0aCI6Ii8zNTg2OTI1Ni8zMTQ5MjgzMDYtODAzNmY0YzItOWZlYi00ZTVhLThjMjktYjJkOWFhODUzYWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDE0MDQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViYjQxOWEzNDc2NzJjZWVhMzRhZjQ3NmEzODVjNDI4N2NmMWIwZjA1ZDRmNzZkNWM2OTViYzk3YTQ0ODkwZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F0imZKyS5AuPHkUXQusS3TMHqRpRZmzEy6bOWQFWxpY)
> 
> Hope this information helps.
Hi, I used this command on the old version code, but only achieved a PSNR of 21.88, am I missing something?
![image](https://github.com/user-attachments/assets/1e476d91-82ee-4707-a0e8-45fed3d31932)

**Comment by shenqianxiang** [comment]
有没有渲染的指令？
