### ISSUE TITLE
submodules是不是缺了文件

### ISSUE THREAD

**Issue by luotingjun** [CVMI-Lab/SC-GS#20]
安装过程中遇到
SC-GS\submodules\diff-gaussian-rasterization\cuda_rasterizer\backward.h(19): fatal error C1083: 无法打开包括文 件: “glm/glm.hpp”: No such file or directory

**Comment by yihua7** [comment]
Hi,
You need `git clone --recursive`  to clone this repo with the submodules.

**Comment by luotingjun** [comment]
你好，我在训练过程中遇到了新问题。
大概在迭代6000次左右会弹出报错：
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
请问如何解决

**Comment by luotingjun** [comment]
你好，我在训练过程中遇到了新问题。
在gui中训练jumpingjack时大概在迭代6000次左右会弹出报错：
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
请问如何解决

**Comment by yihua7** [comment]
Did you change any codes? Actually ANTIALIAS feature is not used in our code and it's the issue about the Pillow version. Maybe you can try another version of Pillow.
