### ISSUE TITLE
Question about the Camera Infos in scene/dataset_readers.py

### ISSUE THREAD

**Issue by JiantengChen** [CVMI-Lab/SC-GS#21]
Hi! Thanks for your great work!

I am currently going through the code and came across the following lines where the field of view variables are assigned in a manner that seems unconventional:

https://github.com/yihua7/SC-GS/blob/26cd57d09598b2f5d951029808a5ac9f0ff4f626/scene/dataset_readers.py#L318-L322

In this snippet, it appears that `FovY` is being set to `fovx` and `FovX` is being set to `fovy`.

Could you please explain the reasoning behind this variable assignment? Is there a specific context or convention being followed that necessitates this approach? 

Thanks for your assistance!

**Comment by yihua7** [comment]
Thank you for your careful check! The code here is not exactly correct but does not matter on DNeRF datasets, where the camera focals on X and Y are the same.

**Comment by JiantengChen** [comment]
Thanks for your reply!
