### ISSUE TITLE
如何train NeRF-DS dataset 

### ISSUE THREAD

**Issue by cdfan0627** [CVMI-Lab/SC-GS#23]
您好，非常感謝您傑出的論文

想請問一下如果要訓練NeRF-DS dataset的話，請問Train跟Evalualuate的指令該如何下。

**Comment by yihua7** [comment]
Hi,
Please refer to the [issue 18](https://github.com/yihua7/SC-GS/issues/18#issuecomment-2011188776) for more information.
The current version may fail to perform normally on certain NeRF-DS scenes, an older version is provided there.
