### ISSUE TITLE
看完文章后有些问题求指教

### ISSUE THREAD

**Issue by mengW6** [CVMI-Lab/SC-GS#26]
您好，我有一些问题还请指点
1、这512个稀疏控制点是如何得到的，他们之间有什么关联性吗？然后是怎么控制稀疏控制点去驱动3D高斯点运动，这输出的动作是随机的吗?
2、请问有没有放出训练好的模型
3、输入的是图片序列吗?
4、跑代码需要多长时间
非常期待和感谢您的回答！

**Comment by yihua7** [comment]
Hi,

1. Control points are initialized as Gaussians and optimized using rendering loss.
2. You can execute the training code directly, which should yield results quickly.
3. Yes.
4. It should take between 10 to 20 minutes.

Feel free to continue this discussion if you have more questions or insights!

**Comment by mengW6** [comment]
Thanks for you reply!
