### ISSUE TITLE
no modules name 'diff- gaussian -rasterization' and 'simple knn'

### ISSUE THREAD

**Issue by mengW6** [CVMI-Lab/SC-GS#29]
Hi， 
    Thanks for sharing your amazing work.When I tried to run the code, I encountered an issue: the two files 'diff- gaussian -rasterization'  and 'simple-knn' in submodules have already been downloaded, but when running train.py and train_gui. py, it still shows that no modules name 'diff- gaussian -rasterization' and 'simple knn'.Do you have any solutions?
    Also, I want to visualize sparse control points, but I couldn't find the code for the control points in which file. Can you give me some guidance?  
    Thank you very much and I look forward to your guidance.

**Comment by yihua7** [comment]
Hi,

- You need to clone this repo recursively like: `git clone --recurse-submodules XXX` to include all submodules.

- Please refer to this repo for simple-knn: https://gitlab.inria.fr/bkerbl/simple-knn. The original one is missing.

- You can simply click the button `Node` (Following the title visualization) on the control panel and visualize control points. You can find the button at the UI frame: https://github.com/yihua7/SC-GS?tab=readme-ov-file#editing
