### ISSUE TITLE
Would it be possible to share the supplementary material please?

### ISSUE THREAD

**Issue by haliphinx** [CVMI-Lab/SC-GS#35]
Hello author, 

Excellent work! And thanks for open source the project.

I'm reading about the paper and I'm wondering if it would be possible to share the supplementary material as mentioned in the main paper as well. That would be really helpful.

**Comment by yihua7** [comment]
Hi, 
Could you give me an e-mail address then I can share the file with you? : )

**Comment by haliphinx** [comment]
> Hi, Could you give me an e-mail address then I can share the file with you? : )

Thanks for the fast reply! Yes, my email is xhu0026@gmail.com.

**Comment by JiantengChen** [comment]
Hi! @yihua7 

Thanks for your great work! I am also looking for supplementary materials and came across this issue. Below is my email address. Could you please share the file with me as well?

chenjiantengx@gmail.com
