### ISSUE TITLE
Where can I obtain the supplementary materials mentioned in the paper?

### ISSUE THREAD

**Issue by yangzhou24** [CVMI-Lab/SC-GS#44]
This is a great job. Where can I obtain the supplementary materials mentioned in your paper? If you could provide it, I would greatly appreciate it!
My email is [yangzhou.gm@gmail](url)

**Comment by yihua7** [comment]
Hi,
Supp file is now available on the homepage as mentioned in https://github.com/yihua7/SC-GS/issues/41#issuecomment-2148307990.

**Comment by YangZhou-CS** [comment]
邮件已收到，谢谢！

**Comment by yangzhou24** [comment]
I have seen the supplementary materials,.Thank you!
