### ISSUE TITLE
If training with GUI, the speed is very slow.

### ISSUE THREAD

**Issue by yangzhou24** [CVMI-Lab/SC-GS#45]
Hello,
I find if training with GUI, the speed is very slow. How to solve? if training with terminal, the speed is normal.
The instruction is 
`CUDA_VISIBLE_DEVICES=0 python train_gui.py --source_path YOUR/PATH/TO/DATASET/jumpingjacks --model_path outputs/jumpingjacks --deform_type node --node_num 512 --hyper_dim 8 --is_blender --eval --gt_alpha_mask_as_scene_mask --local_frame --resolution 2 --W 800 --H 800 --gui`

**Comment by YangZhou-CS** [comment]
I ran the project on a remote server and visualized the GUI through X11 Forwarding.

**Comment by qwer1793** [comment]
Have U solve it？ I met with the same problem...
