### ISSUE TITLE
No loop matching the specified signature 报错，训练了5000步后界面退出

### ISSUE THREAD

**Issue by wing158** [CVMI-Lab/SC-GS#5]
File "D:\miniconda3\envs\ernerf\lib\site-packages\torch\utils\tensorboard\summary.py", line 380, in make_histogram
    cum_counts = np.cumsum(np.greater(counts, 0, dtype=np.int32))
TypeError: No loop matching the specified signature and casting was found for ufunc greater。
环境 ：windows 3090 24g

**Comment by yihua7** [comment]
Hi,
It seems to be an environmental issue of your python.
Could you please provide a more detailed error traceback?

**Comment by yihua7** [comment]
Windows is not recommended as all our code is evaluated on Ubuntu.
The command without GUI may solve your problem:
```
CUDA_VISIBLE_DEVICES=0 python train_gui.py --source_path YOUR/PATH/TO/DATASET/jumpingjacks --model_path outputs/jumpingjacks --deform_type node --node_num 512 --is_blender --eval --gt_alpha_mask_as_scene_mask --local_frame --W 800 --H 800 --random_bg_color --white_background
```

**Comment by yihua7** [comment]
It seems to be related to the compatibility of your tensorboard version.
Can you try (1) removing codes of tensorboard logging or (2) switching tensorboard version to 2.14.0?

**Comment by wing158** [comment]
1.12.1+cu113,  python 3.10 ，tensorboard-2.8.0

**Comment by yihua7** [comment]
> It seems to be related to the compatibility of your tensorboard version. Can you try (1) removing codes of tensorboard logging or (2) switching tensorboard version to 2.14.0?

Could you try these two ways? It should be an environmental issue.

**Comment by wing158** [comment]
谢谢，我先按方法1 移走tensorboard  log

**Comment by yihua7** [comment]
Thanks for pointing out the missing model functionality.
I just commited a version with the save model function (2e843fdb48d87137dfab1484bacadef2b89b0b0c). If any other questions arise, please feel free to contact me~

**Comment by yihua7** [comment]
Hello, do you need any further help with this issue?

**Comment by wing158** [comment]
按方法处理代码已正常运行，谢谢
