### ISSUE TITLE
Deformation

### ISSUE THREAD

**Issue by zhenyuan1234** [CVMI-Lab/SC-GS#50]
Hi, how do controllable points guide 3D Gaussian deformation? Is there any constraint to achieve it? Thanks!

**Comment by yihua7** [comment]
Hi,
Thanks for discussing this. Briefly, the control points affect Gaussians using a learnable RBF determining the control weights. The method is a linear blending skinning (LBS) manner. Some constraints like ARAP regularization are used during training. For more details, please refer to our paper. : )

**Comment by zhenyuan1234** [comment]
Thanks for your sincere reply. I have another question. Why the results evaluated with render.py are worse than the results evaluated during training (on NeRF-DS datasets). Looking forward to your reply.
