### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by zhenyuan1234** [CVMI-Lab/SC-GS#53]
Hi, training with the old code reports the following error while testing. How to solve this problem.

File "render.py", line 46, in render_set
    d_xyz, d_rotation, d_scaling = deform.step(xyz.detach(), time_input, feature=gaussians.feature, is_training=False, motion_mask=gaussians.motion_mask)
ValueError: too many values to unpack (expected 3)

**Comment by yihua7** [comment]
Hi,
It seems a bug of the old version to run render.py. Could you try the train_gui.py instead or transfer the rendering code from train_gui.py to render.py? Sorry about that.

**Comment by zhenyuan1234** [comment]
> Hi, It seems a bug of the old version to run render.py. Could you try the train_gui.py instead or transfer the rendering code from train_gui.py to render.py? Sorry about that.

Can you tell me the details of the above operation? Thanks!
