### ISSUE TITLE
About requirements.txt

### ISSUE THREAD

**Issue by HaoZhiG** [CVMI-Lab/SC-GS#6]
I'm delighted to see the code published and eager to get started. However, I'm encountering some difficulties with dependency installation while trying to train a model. Initially, I installed the dependencies listed in requirements.txt, but when I attempted to train the model, I received errors indicating missing modules such as imageio, plyfile, and pytorch3d. After installing these modules, I encountered another error stating a missing module torch.func.
![image](https://github.com/yihua7/SC-GS/assets/101928950/661239e7-3cd4-4266-9576-8a50d22aca92)

My environment is set up with torch==1.12.1+cu113.

I'd greatly appreciate any guidance or suggestions on how to resolve this issue.

**Comment by yihua7** [comment]
Hi,
Indeed the importing here is unnecessary and I just removed it in the latest commit d77da02270671d31f3f18b3331c763701ec66de9.
Please try the latest code and feel free to ask any questions :)

**Comment by yihua7** [comment]
Thanks for the reminder, I've also added imageio, plyfile, and pytorch3d to requirements.txt (refer to 2d414ce06a71f5284253b537ae2a5d313a7e9582) :)

**Comment by HaoZhiG** [comment]
![image](https://github.com/yihua7/SC-GS/assets/101928950/4d23ddbe-44a1-4ff7-b664-88838cc906d6)
![image](https://github.com/yihua7/SC-GS/assets/101928950/080952eb-c884-48af-9447-1a6cdfce2739)
![image](https://github.com/yihua7/SC-GS/assets/101928950/2857d2ab-3511-48f5-b64a-b052efe2d0e9)
![image](https://github.com/yihua7/SC-GS/assets/101928950/d5f0b7c8-92bc-4b65-a83b-bc598be38e79)
![image](https://github.com/yihua7/SC-GS/assets/101928950/9ee6d1e0-32b1-4764-84a1-17834f12b4d0)

Indeed, there are a few more modules that I encountered needing to be downloaded and installed. But these are specific to my situation and may vary. I just wanted to mention it for reference. Thank you for your assistance!

**Comment by yihua7** [comment]
Great thanks to your feedback!
I supplemented more packages to the requirements.txt. It can definitely benefit every user:)
