### ISSUE TITLE
素材大小有限制吗？ demo里的是800*800

### ISSUE THREAD

**Issue by wing158** [CVMI-Lab/SC-GS#7]
请问demo里一般是800*800,200张图左右， 2K或4K的是否可以，points数里是否有限制？

**Comment by yihua7** [comment]
Hi! :)

1. Our method and code are not limited to any resolution and number of views, but there will be differences in performance and inference speed for different settings of datasets.

2. Higher-resolution training images will result in clearer reconstruction results. A smaller number of training views can easily lead to overfitting of specific sparse views, which is an inherent problem of Gaussian Splatting.
